### ISSUE TITLE
Eval Videos on website - options

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-eval-overview#12]
After processing the input from the [21 Feb EOWG telecon](https://www.w3.org/2020/02/21-eo-minutes.html#item03), I think below is the situation, options, issues, and questions.

Note:
* **Specific Pages** &mdash; The videos will be available on/from the Evaluation Overview pages, as well as specific pages. For example, Video 2 will be on the [Easy Checks page](https://www.w3.org/WAI/test-evaluate/preliminary/)
* **Use Case A** &mdash; User is on the Eval Overview page and wants to watch all of the videos.
* **Use Case Note B** &mdash; With the Perspectives videos and the Intro video, we wanted people share links to them, show them in presentations, etc. This is not nearly as big an expectation/goal for these videos.
* **Implementation limitation** &mdash; We use AblePlayer. It doesn't work well to have multiple instances on one page.

<h2>Provide each video on a separate web page</h2>

Note: We probably also want to provide the videos directly on the pages, with one of the options below.

Pros:
* Lots of flexibility for providing interactive transcripts, descriptive transcripts, link to version on W3C server (for those not able to get YouTube), etc.
* Easy to implement.
* [minor] Easy URI pointer for sharing.

Cons for doing *only* separate pages:
* Poor user experience having to go to separate pages – especially for the Use Case A above: users would go from Overview page, to separate video page, then back to Overview page, then to separate video page, then to back Overview page, etc. - 5 times.

<h2>Option 1: Videos in modal dialog box</h2>

Notes:
* We can choose not to enable AblePlayer’s interactive transcript in the modal to avoid that complication.
* [example accessible modal](http://examples.simplyaccessible.com/gazer/modal.html)

Pros:
* This option provides the best user experience in the opinion of several participants.
* Would work well on Eval Overview page and on the specific pages.

Cons:
* Modal dialog boxes not preferred by at least one participant, primarily because of the coding complexity.
* [potential deal breaker] Might be more complex coding than we want to deal with – especially to get implemented before CSUN.

<h2>Option 2: Videos on page not with AblePlayer</h2>

Notes:
* Would also link to more robust version on separate page.
* Some EOWG participants thought this would be acceptable **_if_** the player on the main page provided basic accessibility.

Open issue:
* [potential deal breaker] Can we do this easily with a sufficiently-accessible player? If we use simple HTML5 video, are the default browser players enough? [input on YouTube player accessibility]( https://docs.google.com/document/d/1sGl-gLg8153M8iynafgGdVqyWy5n_H0CbKiJbllg2Sg/edit#heading=h.nuvi4gyge8ij)

<h3>Option 2a: Videos under expand-collapse (used throughout WAI website)</h3>

* [polished version of that under Introduction](https://deploy-preview-8--wai-eval-overview.netlify.com/test-evaluate/#intro)
* [rough version of that with thumbnails under each section](https://deploy-preview-7--wai-eval-overview.netlify.com/test-evaluate/#intro)

Pros:
* Easy to do with existing WAI site code.
* Decent UI for Use Case A.

Cons:
* [minor] Not common UI for getting videos.

<h3>Option 2b: Videos displayed in small player</h3>

[rough prototype of 2b]( https://deploy-preview-11--wai-eval-overview.netlify.com/test-evaluate/) – which includes link to version with more accessibility features

* Would need to decide on placement and size. Prototype has them right aligned.

Pros:
* For Use Case A, a good user experience.

Cons:
* Doesn’t work well for the specific pages (because frequent/repeat users of the page don't want to have to scroll page the video all the time).

**Comment by nitedog** [comment]
It seems to me that the uses on the overview and individual pages may be somewhat different:

- On the overview pages, most people are looking for information about the resources, and will likely be helped with directly embedded videos that are fully expanded by default (like in option 2b)
- On the individual pages, most first-time users will want to view the video but then probably not after they are used to the resource. Using collapsed approach is probably better (like in option 2a)

Note that the "multiple videos issue" with AblePlayer only applies to the overview page. This issue probably needs to be addressed in a similar way regardless of expand/collapse or modal dialog boxes (all instances of the player need to be fully removed when another is initiated through expanding or opening a modal dialog box). Following that, trying to come up with a modal dialog approach as in option 1 does not seem realistic before CSUN.

I think this leaves us with two aspects to further explore:

1. Define what we mean by "sufficiently accessible" player. We would likely only use that player on the overview page, and could link to the second instance of the same video on the individual/specific page, which will be using AblePlayer. I guess it is sufficient if the player does not cause [interference (eg. keyboard trap) as defined by WCAG](https://www.w3.org/TR/WCAG21/#cc5)?
2. If we cannot find a player that meets this minimum requirement of non-interference, then we will probably have to use the expand/collapse approach for now. @hidde is exploring the coding feasibility/effort required to accomplish that.

**Comment by yatil** [comment]
Of course I defer to the WAI Design team for a specific recommendation, these are just my two cents and my personal view, out of my personal experience:

* I’m still strongly preferring **unlabelled Option 0 (separate pages)** as the con (clicking the back button several times) is not a big burden, especially as it would make the overview page load faster and be less sluggish due to the removed JS. A video player is a huge resource and adding five videos that are all preloaded and initialized to a page adds significant to the time to interaction with the page. 

  It also gives us a neat video overview page that people can share and allows people to share individual videos.

  Last, but far from least, it is consistent with what we do with other videos. Consistency is important, especially for people with cognitive disabilities, but it makes it also easier for screen reader users and a separate page makes using the keyboard interaction simpler, as there are not multiple play buttons, for example.

* I strongly feel that we **must not** use modals at all cost. They are a bad user experience – especially on mobile, are hard to implement and fragile, only work properly for screen reader users if both, browser and assistive tech has ARIA support for them, which is not a given. As [UX Researchers Nielsen Norman](https://www.nngroup.com/articles/modal-nonmodal-dialog/) put it: “modal dialogs become problematic when used for noncritical activities”. 

  A modal in this case gives you all the disadvantages of a new page (user out of the flow, not having the overview page on the screen, having to navigate back and forth between the video and the page) without the standard behavior that comes with a page change: A consistent back button, clear purpose of the page, inability to accidentally close the modal when pressing ESC, more space on mobile as there’s no need for a mobile “chrome”.

  I have assessed many modals in the last three years and I have never seen a good implementation. I have seen different levels of mediocre implementations but I cannot say that it made the page easier to use.

**Comment by hidde** [comment]
With my developer hat on: 

- there are plenty of ways to do accessible modal dialogs, but there are also a number of not entirely solved/agreed upon accessibility problems, especially if we do modals in modals (but as @slhenry we could turn AblePlayer's modal off). Regardless, adding a new element like that to the WAI design components would require some back and forth (i.e time)
- I have to balance this with my other pre-CSUN commitments; implementation of a modal with videos or multiple AblePlayers on one WAI page does not fit in my work schedule. 
- I would be able to implement 2b with YouTube players (we could also upload the captions in YouTube and have them available in that player)

With my EOWG participant hat on: 

- I like the right aligned players on overview page as in @slhenry's example 2b
- I like linking to individual pages that contain an AblePlayer with the same video + text transcript + captions.

**Comment by slhenry** [comment]
**Proposal:**

After more discussion among editor, coder, WAI site design owner, and EOWG Chairs, we propose the following for now before CSUN. We also plan to further consider other options for another iteration in the near future.

_Note:_ The prototypes have other videos for now, not the actual evaluation videos and thumbnails.

<h2>Evaluation Overview page</h2>

**[rough prototype of layout](https://deploy-preview-11--wai-eval-overview.netlify.com/test-evaluate/)** _(ignore the float clear bugs)_

1. The videos will be always shown. (no expand-collapse for the videos overall)
2. The videos will be float-right.
3. The first video will be in AblePlayer. The descriptive transcript will be under an expand-collapse below the video, default collapsed.
4. The other videos will be in either HTML5video that uses browser player or YouTube player. (More on that is in a separate issue: @@ video embed options.) Right under the video will be a link to an accessible version with AblePlayer. That will link to the video in the specific page, e.g., Easy Checks.

<h2>Specific pages</h2>
(Easy Checks, Selecting Tools, WCAG-EM Overview, Involving Users)

**[rough prototype on WCAG-EM Overview](https://deploy-preview-2--wai-wcag-em-overview.netlify.com/test-evaluate/conformance/wcag-em/#video-web-accessibility-conformance-evaluation-overview)**

5. The video will be in AblePlayer under the first main heading on the page, with expand-collapse. By default it is collapsed. The descriptive transcript will be under an expand-collapse below the video, default collapsed.
6. The heading with thumbnail will appear as the first item under "Page content". Note that if you click that in the page contents, it goes down to the video with the section expanded.
7. ...
8. ...


1.

**Comment by slhenry** [comment]
(A thought so I don't lose it: Maybe for future iteration, the videos are not shown by default and there is a big, clear button to show them? That is, they are not loaded at all unless the user asks for them. This would decrease page load, yet add more UI and user interaction...)

**Comment by slhenry** [comment]
[more details in wiki page](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/on_WAI-website#Background)
