### ISSUE TITLE
Add evaluation videos

### ISSUE THREAD

**Issue by hidde** [w3c/wai-eval-overview#14]
This describes the work (done and to do) for deploying the evaluation videos to the WAI website. 

Some of the work is done in other repositories, keeping track of it in this issue for sanity.

## Add videos to evaluation overview page (in `w3c/wai-eval-overview`)

**[Preview of evaluation overview page](https://deploy-preview-21--wai-eval-overview.netlify.com)**

- [x] Add AblePlayer floated right, open, with underneath a link to text transcript that lives in an expand collapse, that is collapsed by default, at the bottom of this page
- [x] Include [transcript from wiki](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/descriptive_transcripts#Video_1:_Evaluation_Overview)
- [x] Shawn - Supply correct YouTube URL for Overview video (placeholder ones for now -- replace with news ones when get)
- [ ] Include correct YouTube URL for Overview video (placeholder ones for now -- replace with news ones when get)
- [x] Link to video file on W3C server
- [x] Create new reusable ‘video card’ component: includes support for a HTML `<video>` with video and captions, plus a link to accessible version, floats right on larger screens, clears `float` via following `h2` and `aside`
- [x] include poster image for later 4 using HTML5 video

###  Add right floated video players (`<video>`) with links to more accessible versions on underlying pages

<a href="https://deploy-preview-15--wai-eval-overview.netlify.com/test-evaluate/"><img width="987" alt="screenshot of initial checks header and content with player floated on right" src="https://user-images.githubusercontent.com/178782/75974471-1e722c80-5ed7-11ea-875a-ad7520b7775b.png"></a>

- [x] get (or convert) VTT files (instead of srt) 
- [x] Initial Checks / Preliminary Evaluation to `/WAI/test-evaluate/preliminary/`, with video and captions  `http://media.w3.org/wai/evaluation-intros/easy-checks-accessibility-cc.srt` and `http://media.w3.org/wai/evaluation-intros/easy-checks-accessibility.mp4`
- [x] Tools to `/WAI/test-evaluate/tools/` with video `http://media.w3.org/wai/evaluation-intros/tools-for-evaluating.mp4` and captions `http://media.w3.org/wai/evaluation-intros/tools-for-evaluating-cc.srt`
- [x] Conformance Evaluation to `/WAI/test-evaluate/conformance/`. with video `http://media.w3.org/wai/evaluation-intros/conformance-evaluation.mp4` and captions `http://media.w3.org/wai/evaluation-intros/conformance-evaluation-cc.srt`
- [x] People to `/WAI/test-evaluate/involving-users/`  with video `http://media.w3.org/wai/evaluation-intros/involving-users.mp4` and captions `http://media.w3.org/wai/evaluation-intros/involving-users-cc.srt`

## Add videos to evaluation tools overview page (in `w3c/wai-eval-tools-overview`)

[Preview of Tools Overview Page](https://deploy-preview-4--wai-eval-tools-overview.netlify.com)

- [x] Add AblePlayer floated right, open, with underneath a link to text transcript that lives in an expand collapse, that is collapsed by default, at the bottom of this page (as described in https://github.com/w3c/wai-eval-overview/issues/19)
- [x] [maintenance] add Netlify to `wai-eval-tools-overview` repository, fix the build
- [ ] Use correct YouTube URL -- replace when we get them

## Add videos to conformance overview page (in `w3c/wai-conformance-eval-overview`)

[Preview of Conformance Overview Page](https://deploy-preview-3--wai-conformance-eval-overview.netlify.com/test-evaluate/conformance/)

- [x] Add AblePlayer floated right, open, with underneath a link to text transcript that lives in an expand collapse, that is collapsed by default, at the bottom of this page (as described in https://github.com/w3c/wai-eval-overview/issues/19)
- [x] [maintenance] add Netlify to `wai-conformance-eval-overview` repository, fix the build
- [ ] Use correct YouTube URL -- replace when we get them

## Add videos to sub pages

On sub pages, the video will display under the first heading, in an expand collapse, labelled: **Video: [name of video]**.

<img width="587" alt="Screenshot 2020-03-05 at 11 12 40" src="https://user-images.githubusercontent.com/178782/75971620-52971e80-5ed2-11ea-9006-7c646185f219.png">

It is closed by default.

Inside the collapsing part, there is:

* AblePlayer instance with video hosted on YouTube
* Expand collapse with a text transcript taken from [wiki](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/descriptive_transcripts)

### Video: “Preliminary Evaluation” / Easy Checks / Initial Checks

Prepare:

* [x] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube, URL: @@ 
* [x] Upload caption ([caption for preliminary evaluation](http://media.w3.org/wai/evaluation-intros/easy-checks-accessibility-cc.srt))
* [x] Upload text transcript ([transcript for preliminary evaluation](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/descriptive_transcripts#Video_2:_Preliminary_Evaluation))

List on pages:

* [x] [Easy Checks](https://www.w3.org/WAI/test-evaluate/preliminary/) 
* [ ] Ensure this uses final versions of: YouTube ID, link to video on W3C server, link to captions,  transcript and thumbnail image

### Video: “Selecting and Using Tools” / Tools

Prepare:

* [x] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube, URL: @@ 
* [x] Upload caption 
* [x] Upload text transcript

List on pages:

* [ ] [Selecting Tools](https://www.w3.org/WAI/test-evaluate/tools/selecting/)
* [ ] Ensure this uses final versions of: YouTube ID, link to video on W3C server, link to captions,  transcript and thumbnail image

### Video: “Comprehensive Evaluation” / Conformance evaluation

Prepare:

* [x] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube, URL: @@ 
* [x] Upload caption
* [x] Upload text transcript

List on pages:

* [x] WCAG EM Overview (Pull request: https://github.com/w3c/wai-wcag-em-overview/pull/2, preview: https://deploy-preview-2--wai-wcag-em-overview.netlify.com)
* [ ] Ensure this uses final versions of: YouTube ID, link to video on W3C server, link to captions,  transcript and thumbnail image

### Video: “Involving Users”

Prepare:

* [x] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube, URL: @@ 
* [x] Upload caption
* [x] Upload text transcript

List on pages:

* [ ] [Involving Users in Evaluation](https://www.w3.org/WAI/test-evaluate/involving-users/)
* [ ] Ensure on Involving Users in Evaluation, this uses final versions of: YouTube ID, link to video on W3C server, link to captions,  transcript and thumbnail image
* [ ] [Involving Users in Planning](https://www.w3.org/WAI/planning/involving-users/) (on this page it is just a link, @slhenry to add)

## Update and add related info

- [ ] update footer on all pages
- [ ] add [Ack page](https://github.com/w3c/wai-eval-overview/pull/9)

**Comment by slhenry** [comment]
## 2 of 2: Add videos to sub pages

On sub pages, the video will display under the first heading, in an expand collapse, labelled: **Video: [name of video]**.

<img width="587" alt="Screenshot 2020-03-05 at 11 12 40" src="https://user-images.githubusercontent.com/178782/75971620-52971e80-5ed2-11ea-9006-7c646185f219.png">

It is closed by default.

Inside the collapsing part, there is:

* AblePlayer instance with video hosted on YouTube
* Expand collapse with a text transcript taken from [wiki](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/descriptive_transcripts)

### Video: “Preliminary Evaluation” / Easy Checks / Initial Checks

Prepare:

* [ ] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube (@slhenry), URL: @@ 
* [x] Upload caption ([caption for preliminary evaluation](http://media.w3.org/wai/evaluation-intros/easy-checks-accessibility-cc.srt))
* [x] Upload text transcript ([transcript for preliminary evaluation](https://www.w3.org/WAI/EO/wiki/Video-Based_Resources/Evaluation_Introduction/descriptive_transcripts#Video_2:_Preliminary_Evaluation))

List on pages:

* [ ] TBD 

### Video: “Selecting and Using Tools” / Tools

Prepare:

* [ ] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube(@slhenry), URL: @@ 
* [x] Upload caption 
* [x] Upload text transcript

List on pages:

* [ ] TBD

### Video: “Comprehensive Evaluation” / Conformance evaluation

Prepare:

* [ ] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube(@slhenry), URL: @@ 
* [x] Upload caption
* [x] Upload text transcript

List on pages:

* [ ] TBD

### Video: “Involving Users”

Prepare:

* [ ] Create thumbnail
* [x] Upload to W3C media server
* [ ] Upload to YouTube(@slhenry), URL: @@ 
* [x] Upload caption
* [x] Upload text transcript

List on pages:

* [ ] TBD

**Comment by hidde** [comment]
@slhenry @nitedog The evaluation videos have been added to the three overview pages and the five sub/specific pages.

Individual pull requests and previews are listed in the issue text, or you can find them above this comment (under “This was referenced” with their status). 

What should be correct: 

- footers
- the UI patterns used (overview pages have videos floated right, sub/specific pages have them in an expand collapse with inside of those another expand collapse with text transcript)

What's still missing in all off these pull requests: 

- correct YouTube ID
- correct link to file on W3C server (+ correct file size)
- correct link to captions in VTT
- correct transcript 
- correct thumbnail (for sub/specific pages)

Whenever these are ready, I am happy to add them, or feel free to commit directly to the branches these changes exist in. 

For comments on specific previews, please reply in the open Pull Requests, for general comments, please reply here.

**Comment by hidde** [comment]
Links to all previews:

Overview pages:

* [Preview of evaluation overview page](https://deploy-preview-17--wai-eval-overview.netlify.com)
* [Preview of Tools Overview Page](https://deploy-preview-4--wai-eval-tools-overview.netlify.com)
* [Preview of Conformance Overview Page](https://deploy-preview-3--wai-conformance-eval-overview.netlify.com/test-evaluate/conformance/)

Sub pages: 

* [WCAG EM](https://deploy-preview-2--wai-wcag-em-overview.netlify.com)

**Comment by slhenry** [comment]
For the previews:
* [ ] transcript – available since last week :-)
* [ ] link to file on W3C server (+ correct file size) – the links and sizes shouldn’t change
* [ ] thumbnail (for sub/specific pages) – please use what I sent (then I can change the two images directly in GitHub)
* [ ] link to captions in VTT – I converted the srt files. used same filenames. should be updated on server by Thursday morning
* [ ] YouTube ID – please use the links I sent. some may not change

before publishing:
* [ ] SLH - update thumbnails (probably only 2)
* [ ] SLH - finalize videos on YouTube (latest version, add metadata, captions, new thumbnails)
* [ ] anyone - update YouTube IDs as needed

**Comment by hidde** [comment]
Thank you, Shawn! I will add all these tomorrow.

**Comment by hidde** [comment]
Update:

On the PRs for the overview pages, I have added transcripts, links to files, file sizes, thumbnails, captions and YouTube IDs.

Note: the AblePlayers do break now, because of invalid VTTs (they do not get served on our preview URL, because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)), I have reported a bug with AblePlayer. This should go away on the live site. (This did not happen before, because we did not include any captions).

**Comment by hidde** [comment]
Update: 

On the PRs for the sub/specific pages, I have now also updated transcripts, links to files, file sizes, thumbnails, captions and YouTube IDs.

@slhenry I've added the thumbnails using the [Image Component](https://wai-website-theme.netlify.com/components/images/), which also takes care of size and border rounding (so I could remove inline CSS that did that). One thing that component doesn't do is `vertical-align:middle`, do you feel strongly about that? (If so I can add a rule to the `wai-website-theme` that applies it in our situation, i.e. when used inside a heading in expand/collapse)

**Comment by slhenry** [comment]
> @slhenry I've added the thumbnails using the Image Component, which also takes care of size and border rounding (so I could remove inline CSS that did that). One thing that component doesn't do is vertical-align:middle, do you feel strongly about that? (If so I can add a rule to the wai-website-theme that applies it in our situation, i.e. when used inside a heading in expand/collapse)

@hidde Do you mean the position of the video thumbnail in the [headings and TOC like here](https://deploy-preview-24--wai-selecting-eval-tools.netlify.app/test-evaluate/tools/selecting/#video)?

They look great to me!

**Comment by slhenry** [comment]
I started at the [11 March comment above](https://github.com/w3c/wai-eval-overview/issues/14#issuecomment-597717032)

I edited the 7 pages, including:
* [x] edited names of videos (e.g., “Video: Preliminary Evaluation” -> “Video: Easy Checks Overview”;  and “Video: Selecting and Using Tools” -> “Video: Evaluation Tools Overview”)
* [x] on main Overview page, for links to videos on other pages, added “#video-intro” so it goes right to the video.
And on pages missing that id, added it.
* [x] changed dates to leave main content updated date and video added date for content pages
* [x] checked/added link in footer text: <a href="./acknowledgements/">Acknowledgements</a>
* [x] checked/added footer text: Note about video description…
* [x] added new videos to YouTube, with new thumbnails, and updated links
* [x] updated thumbnails in GitHub
   * [ ] **[open]** add thumbnail for overview (even though not using it, so it's there for the future)
* [x] changed captions file pointers from srt to vtt
* [x] made consistent the links to video on W3C server
* [x] updated videos on W3C server

Pending a fresh QA check, I think they are done from a wording point-of-view. (Technical issues in next comment.)

**Comment by slhenry** [comment]
There are several technical issues.

* [ ] **Controls not displaying in Able Player.**<br>I see above:
> Note: the AblePlayers do break now, because of invalid VTTs (they do not get served on our preview URL, because of CORS), I have reported a bug with AblePlayer. This should go away on the live site.

Especially given the challenges with updating the site now, I'd really like to be able to fully test the previews. "should go away on the live site" doesn't feel certain enough. :) What are options? (including possibly contacting AblePlater Terrill directly?)

I note that the AblePlayer controls do show on [this preview](https://deploy-preview-66--wai-video-standards-and-benefits.netlify.app/videos/standards-and-benefits/).
Is it because that page uses VTTs in GitHub, and the eval previews use VTTs on media.org?

If so, is it worth putting the VTTs on GitHub and pointing to them there? Or, are you really certain that it will work live? :-)


* [ ] some links have "https:" and some do not, e.g.,

> captions="//media.w3.org/wai/evaluation-intros/tools-for-evaluating-cc.vtt" (tools overview)

vs.

> captions="https://media.w3.org/wai/evaluation-intros/conformance-evaluation-cc.vtt" (most others)

*Which is correct*?

**Comment by hidde** [comment]
@slhenry Either is fine, I've used `//` to avoid having “mixed content” (as in, a mix of secure and non secure). We should be serving everything over HTTPS, so `https://` should be fine too.

@slhenry @nitedog  I have updated [all PRs](https://github.com/w3c/wai-eval-overview/issues/14#issuecomment-597717032) with local VTTs.

This fixes: 

* Controls not showing in AblePlayer
* CC button not enabled on HTML videos

It looks like the issue was due to CORS, as we discussed before, serving the subtitles from the same origin fixes it (for our previews).

**Comment by slhenry** [comment]
I'm still getting the [CC] crossed out -- in Windows Firefox.

Also, I see above> * [ ] include poster image for later 4 using HTML5 video

Would that show the image once the video is loaded, too? If so, that would also take care of https://github.com/w3c/wai-eval-overview/issues/22

**Comment by hidde** [comment]
> I'm still getting the [CC] crossed out -- in Windows Firefox.

I see it too, but when I click the crossed CC, I am able to choose captions and watch the video with them.

> Would that show the image once the video is loaded, too? If so, that would also take care of #22

Yes! Basically we'd add `poster="any-image-we-like.png"` to the `<video>` element.

**Comment by hidde** [comment]
I've added the capability for our [video card component](https://wai-website-theme.netlify.app/components/video-card/) to have a `poster` attribute, testing if this works in PR https://github.com/w3c/wai-eval-overview/pull/23.

**Comment by slhenry** [comment]
I think only the HTML videos on the main overview page need posters.

The videos using AblePlayer and YouTube get the first image from YouTube, so those are all set!

**Comment by hidde** [comment]
Posters are now added (see https://github.com/w3c/wai-eval-overview/issues/22).

**Comment by hidde** [comment]
Update (cc @nitedog): 

* Added missing captions for initial checks
* For HTML videos, turned on captions by default
* Abbreviated "This video is available in other formats with more accessibility features: ..." to "This video is available with more accessibility features: ..."

**Comment by slhenry** [comment]
I think this is all done (a while ago) !
