### ISSUE TITLE
Thumbnails for HTML videos

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-eval-overview#22]
https://deploy-preview-21--wai-eval-overview.netlify.app/test-evaluate/

The AblePlayer video (1) shows the "thumbnail".

The next 4 currently show the first scene, which is just a blank light-blue screen. It would be nice if those also showed their thumbnails.

@hidde Is this hard or easy?  (Not high priority if hard.)

(fyi @nitedog )

**Comment by hidde** [comment]
The thumbnails are now also shown in the HTML video players, as of commit https://github.com/w3c/wai-eval-overview/pull/21/commits/2eb7cea03d83d2be2a9a652d72306912099e8d85. 

This work lives in PR https://github.com/w3c/wai-eval-overview/pull/21 ([preview PR 21](https://deploy-preview-21--wai-eval-overview.netlify.app/test-evaluate/)).
