### ISSUE TITLE
[ED] please add ACT Rules repository

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-eval-overview#3]
Ref: https://w3c.github.io/wcag-act-rules/

In the "conformance evaluation" section, after WCAG-EM, please add the link above as:

> [Accessibility Conformance Testing (ACT) Rules Repository] - collection of commonly agreed on testing "rules", to help you develop evaluation tools and manual evaluation methodologies more effectively. (Currently in development)

**Comment by yatil** [comment]
Hi @nitedog,

I’m just seeing this. I’ll put it on my todo list. If you assign things like this to me, I’ll get notified and can act more quickly :-)

Eric

**Comment by slhenry** [comment]
a while ago we added it under link to standards.

nitedog, reopen if you want something done differently
