### ISSUE TITLE
[es] update needed

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-overview#36]
Hi @rumoroso 

We will be promoting translations the week of 17 May, along with Global Accessibility Awareness Day (GAAD).

Would you be able to update this translation? Or, should we ask someone else to update it?

https://raw.githubusercontent.com/w3c/wai-eval-overview/master/content/index.es.md

I added the new text in English:
* 2 paragraphs in the footer (which is near the top of the file :-)
* a paragraph with "ATAG Report Tool"
* and the video info and transcript at https://www.w3.org/WAI/test-evaluate/es#alternatives

We have someone translating the subtitle file -- which is the same as the first column in the table. So you could use that when it's done. :-) Let me know what questions you have.

**Comment by shawna-slh** [comment]
Hi @cmuncharaz I haven't heard anything from rumoroso

(same issue with the table -- we don't have the subtitle file yet)

**Comment by rumoroso** [comment]
Hi @shawna-slh , sorry for this late answer. I didn't receive any notification (even when you explicitly mentioned me in the first message). I could take care of it if it is not too late.

**Comment by shawna-slh** [comment]
@rumoroso  Thank you! We are promoting translations this week.

@cmuncharaz Let us know if you have not worked on this yet. We want to avoid duplicate effort.

**Comment by cmuncharaz** [comment]
Dear @shawna-slh,

I did not work on this, so please go ahead @rumoroso.

**Comment by shawna-slh** [comment]
closed with https://github.com/w3c/wai-eval-overview/pull/43
