### ISSUE TITLE
Accessibility Insights report sill shows "..tests that cover all the WCAG 2.1 AA success criteria" instead of WCAG 2.2 

### ISSUE THREAD

**Issue by jasvindargillQA** [w3c/wai-eval-overview#65]
Latest version of A11y Insights have WCAG 2.2 criteria tests listed in full assessment. However when we generate the report it still says WCAG 2.1.

Sample heading from report:
_"This report shows the overall accessibility of the website or web app through a combination of automated and manual tests that cover all the **WCAG 2.1 AA success criteria**."_

**Comment by shawna-slh** [comment]
Hi @jasvindargillQA A11y Insights is not a W3C tool. You would need to contact the vendor of that tool to get it corrected.
